# --- !Ups

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username VARCHAR(256) UNIQUE,
	public_key VARCHAR(1024) UNIQUE
);

CREATE TABLE readings (
  id SERIAL PRIMARY KEY,
  net_in_wh INTEGER NOT NULL,
  read_time TIMESTAMP WITH TIME ZONE NOT NULL,
  signature VARCHAR(1024) NOT NULL,
  user_id INTEGER REFERENCES users ON DELETE CASCADE
);

# --- !Downs

DROP TABLE readings;
DROP TABLE users;
